development:
  adapter: postgresql
  encoding: unicode
  database: fandagr_development
  pool: 5
  username: Ykat
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: fandagr_test
  pool: 5
  username: Ykat
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: fandagr_production
  pool: 5
  username: Ykat
  password:
  host: localhost