development:
  adapter: postgresql
  encoding: unicode
  database: fandangr_development
  pool: 5
  username: Ykat
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: fandangr_test
  pool: 5
  username: Ykat
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: fandangr_production
  pool: 5
  username: Ykat
  password:
  host: localhost